# Generated by Django 5.1.1 on 2024-10-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor_registration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
